"""Optuna-driven multi-objective search over training-free projection edits."""

from heretic_dit.search.editing import (
    InterpolationKernel,
    LayerEdit,
    ProjectionTarget,
    alpha_kernel,
    applied_edit,
    apply_alpha,
    apply_edits,
    cross_attention_targets,
    resolve_alphas,
    resolve_targets,
    restore_edits,
)
from heretic_dit.search.optuna_objective import (
    BENIGN_CONCEPT_PROMPTS,
    ConceptScorer,
    DenoisingLossScorer,
    DictSubspaceProvider,
    GenerativeValidator,
    RecallClassifier,
    ReferenceMatchScorer,
    SubspaceEntry,
    SubspaceProvider,
    TrialConfig,
    benchmark_trial,
    build_objective,
    create_study,
    resolve_subspace,
)

__all__ = [
    "InterpolationKernel",
    "LayerEdit",
    "ProjectionTarget",
    "alpha_kernel",
    "applied_edit",
    "apply_alpha",
    "apply_edits",
    "cross_attention_targets",
    "resolve_alphas",
    "resolve_targets",
    "restore_edits",
    "BENIGN_CONCEPT_PROMPTS",
    "ConceptScorer",
    "DenoisingLossScorer",
    "DictSubspaceProvider",
    "GenerativeValidator",
    "RecallClassifier",
    "ReferenceMatchScorer",
    "SubspaceEntry",
    "SubspaceProvider",
    "TrialConfig",
    "benchmark_trial",
    "build_objective",
    "create_study",
    "resolve_subspace",
]